name       : bind-utils
version    : 9.11.5_p1
release    : 15
source     :
    - ftp://ftp.isc.org/isc/bind9/9.11.5-P1/bind-9.11.5-P1.tar.gz : 6cd6dbf016569f12d4a0ed629e44e895d9ed41c6908274ed2e617666c5491928
license    : MPL-2.0
component  : network.util
summary    : Client side programs nslookup, dig and host.
networking : yes
description: |
    Client side programs nslookup, dig and host.
setup      : |
    %configure --disable-static
build      : |
    %make -C lib/dns
    %make -C lib/isc
    %make -C lib/bind9
    %make -C lib/isccfg
    %make -C lib/lwres
    %make -C bin/dig
    %make -C bin/nsupdate
install    : |
    %make_install -C bin/dig
    %make_install -C bin/nsupdate
