name       : bind-utils
version    : 9.11.4
release    : 11
source     :
    - ftp://ftp.isc.org/isc/bind9/9.11.4/bind-9.11.4.tar.gz : 595070b031f869f8939656b5a5d11b121211967f15f6afeafa895df745279617
license    : MPL-2.0
component  : network.util
summary    : Client side programs nslookup, dig and host.
networking : yes
description: |
    Client side programs nslookup, dig and host.
setup      : |
    %configure --disable-static
build      : |
    %make -C lib/dns
    %make -C lib/isc
    %make -C lib/bind9
    %make -C lib/isccfg
    %make -C lib/lwres
    %make -C bin/dig
    %make -C bin/nsupdate
install    : |
    %make_install -C bin/dig
    %make_install -C bin/nsupdate
