name       : bind-utils
version    : 9.11.0_p3
release    : 4
source     :
    - ftp://ftp.isc.org/isc/bind9/9.11.0-P3/bind-9.11.0-P3.tar.gz : 0feee0374bcbdee73a9d4277f3c5007622279572d520d7c27a4b64015d8ca9e9
license    : ISC
component  : network.util
summary    : Client side programs nslookup, dig and host.
description: |
    Client side programs nslookup, dig and host.
setup      : |
    %configure
build      : |
    %make -C lib/dns
    %make -C lib/isc
    %make -C lib/bind9
    %make -C lib/isccfg
    %make -C lib/lwres
    %make -C bin/dig
install    : |
    %make_install -C bin/dig
