name       : bind-utils
version    : 9.11.4_p2
release    : 13
source     :
    - ftp://ftp.isc.org/isc/bind9/9.11.4-P2/bind-9.11.4-P2.tar.gz : a85af7b629109d41285c7adeae1515daac638bbe4d5dc30d1f4b343dff09d811
license    : MPL-2.0
component  : network.util
summary    : Client side programs nslookup, dig and host.
networking : yes
description: |
    Client side programs nslookup, dig and host.
setup      : |
    %configure --disable-static
build      : |
    %make -C lib/dns
    %make -C lib/isc
    %make -C lib/bind9
    %make -C lib/isccfg
    %make -C lib/lwres
    %make -C bin/dig
    %make -C bin/nsupdate
install    : |
    %make_install -C bin/dig
    %make_install -C bin/nsupdate
